sudo: required
dist: trusty

node_js:
  - "6"
  - "5"
  - "4"

language: node_js

addons:
  code_climate:
    repo_token: ef9a01af5ee4c471d6b256e0e9c0ee641f541ada9dc02f887e4ca138c8b78457

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info